### ISSUE TITLE
Get Area Reports while unlogged

### ISSUE THREAD

**Issue by eMerzh** [njulemon/samy#35]
Hello @njulemon  👋  
We've met briefly in Carto WG...
I find this really interesting, and I, we in Braine-l'Alleud, are thinking about how we deal with reports & stuff...

We are experimenting with Umap to display the small number of cycle path, 
and I was trying to display a map of "dangerous" points in them... I directly thought to Samy for that.

i found the https://www.samy-app.be/api/report/?timestamp_creation__gte=&timestamp_creation__lte=&area=55 api  thingy, but i can't plug in umap as it need a session... 

Would you be open to have the ability to fetch a list of report without requiring a session ? or maybe with a token of some sort?

I'm not really sure why it requires a session in the first place 🤔 

Thanks :)

**Comment by njulemon** [comment]
Hello, 

It is possible. 

This one does not need authentication, and does not add CORS policy (you can deactivate the Proxy on UMap for quick update). 
https://www.samy-app.be/api/report-geojson/?area=WATERMAEL&format=json

**Comment by eMerzh** [comment]
Oooh very nice... sorry for the noise ... closing :)
